import * as Yup from 'yup';

const initialValues = {
  "Account Type": "",
  "Portfolio/Strategy Name": "",
  "Fund Fees Category": "",
  "Investment Category": "",
  "Communication Address": "",
  "Country of Tax Residency": "",
  "No. of Account Holders": "",
  "Quantum of Investment": "",
  "Investment Mode": "",
  "Applicant Name": "",
  "Contact No": "",
  "Enter OTP": "",
  "Email Id": "",
  "PAN No": "",
  "Number of Nominees": "",
  "Bank Name": "",
  "Account No": "",
  "Account Title": "",
  "Bank IFSC Code": "",
  "Nominee Name": "",
  "Nominee PAN": "",
  "Nominee Email Id": "",
  "Nominee Relationship with 1st Applicant": "",
  "DOB": "",
  "Nominee (%)": "",
  "Investment Experience": "",
  "Investment Style": "",
  "How would you react if well diversified portfolio fells below 10%": "",
  "Investment Objective": "",
  "Risk Tolerance": "",
  "Investment Horizon": ""
};

const initialStates = {
  "Account Type": "",
  "Portfolio/Strategy Name": "",
  "Fund Fees Category": "",
  "Investment Category": "",
  "Communication Address": "",
  "Country of Tax Residency": "",
  "No. of Account Holders": "",
  "Quantum of Investment": "",
  "Investment Mode": "",
  "Applicant Details":"" ,
    "Applicant Name": "",
    "Contact No": "",
    "Enter OTP": "",
    "Email Id": "",
    "PAN No": "",


  "Number of Nominees": 1,
  "Nominee Details":"",
    "Nominee Name": "",
        "Nominee PAN": "",
        "Nominee Email Id": "",
        "Contact no":"",
        "Nominee Relationship with 1st Applicant": "",
        "DOB": "",
        "Nominee (%)": "",
  
  "Bank Name": "",
  "Account No": "",
  "Account Title": "",
  "Bank IFSC Code": "",
 
  "Investment Experience": "",
  "Investment Style": "",
  "How would you react if well diversified portfolio fells below 10%": "",
  "Investment Objective": "",
  "Risk Tolerance": "",
  "Investment Horizon": ""
};

const ApplicationDetailState = {  
    "Applicant Name": "",
    "Contact No": "",
    "Enter OTP": "",
    "Email Id": "",
    "PAN No": "",
}

const NomineeDetailState = { 
  "Nominee Name": "",
      "Nominee PAN": "",
      "Nominee Email Id": "",
      "Contact no":"",
      "Nominee Relationship with 1st Applicant": "",
      "DOB": "",
      "Nominee (%)": "",
}

const validationSchema = Yup.object().shape({
  "Account Type": Yup.string().required('Required'),
  "Portfolio/Strategy Name": Yup.string().required('Required'),
  "Fund Fees Category": Yup.string().required('Required'),
  "Investment Category": Yup.string().required('Required'),
  "Communication Address": Yup.string().required('Required'),
  "Country of Tax Residency": Yup.string().required('Required'),
  // "No. of Account Holders": Yup.string().required('Required'),
  "Quantum of Investment": Yup.number().required('Required').min(0, 'Should be at least 0'),
  "Investment Mode": Yup.string().required('Required'),
  "Applicant Name": Yup.string().required('Required'),
  "Contact No": Yup.string().matches(/^\d{10}$/, 'Contact number must be exactly 10 digits').required('Contact number is required'),
  "Enter Contact OTP": Yup.string().required('Required'),
  "Email Id": Yup.string().email('Invalid email address').required('Required'),
  "Enter Email OTP": Yup.string().required('Required'),
  "PAN No": Yup.string().matches(/^([A-Z]){5}([0-9]){4}([A-Z]){1}?$/, 'Invalid PAN').required('Required'),
  // "Number of Nominees": Yup.number().required('Required').min(0, 'Should be at least 0'),
  "Bank Name": Yup.string().required('Required'),
  "Account No": Yup.string().required('Required'),
  "Account Title": Yup.string().required('Required'),
  "Bank IFSC Code": Yup.string().required('Required'),
  "Nominee Name": Yup.string().required('Required'),
  "Nominee PAN": Yup.string().matches(/^([A-Z]){5}([0-9]){4}([A-Z]){1}?$/, 'Invalid PAN').required('Required'),
  "Nominee Email Id": Yup.string().email('Invalid email address').required('Required'),
  "Nominee Relationship with 1st Applicant": Yup.string().required('Required'),
  "Nominee (%)": Yup.number().required('Required').min(0, 'Should be at least 0').max(100, 'Should be at most 100'),
  "Investment Experience": Yup.string().required('Required'),
  "Investment Style": Yup.string().required('Required'),
  "How would you react if well diversified portfolio fells below 10%": Yup.string().required('Required'),
  "Investment Objective": Yup.string().required('Required'),
  "Risk Tolerance": Yup.string().required('Required'),
  "Investment Horizon": Yup.string().required('Required'),
});

export { initialValues, validationSchema ,initialStates,NomineeDetailState,ApplicationDetailState };
